### Let's compare performance of my Gradient Boosting Regressor implementation with Gradient Boosting Regressor from sklearn

In [1]:
import pandas as pd

data = pd.read_csv('data.csv')
data

,age,income,dependents,has_property,has_car,credit_score,job_tenure,has_education,loan_amount,loan_period,delay_days
0,76,32181,3,0,1,814,28,1,142434,1770,-4
1,69,52789,8,1,0,501,28,1,120887,1590,7
2,19,70535,1,0,1,325,26,1,188766,810,0
3,31,85271,1,0,1,525,29,1,406792,330,-8
4,18,19974,2,0,1,618,34,1,155240,1560,43
...,...,...,...,...,...,...,...,...,...,...,...
9995,37,81720,9,1,0,442,14,1,545892,1290,10
9996,73,63861,1,1,1,853,34,0,182648,180,0
9997,21,45667,7,0,1,619,4,1,106619,930,3
9998,49,85144,1,1,1,366,19,0,275711,1080,0
9999,45,56294,3,0,0,844,1,1,142409,960,2

In [2]:
from sklearn.ensemble import GradientBoostingRegressor as sklearn_regressor
from gradient_boosting import GradientBoostingRegressor as my_regressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import pandas as pd

X, y = data.drop('delay_days', axis=1), data['delay_days']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

sklearn_regr = sklearn_regressor(
    loss='squared_error',
    learning_rate=0.1,
    n_estimators=100,
    max_depth=3,
    min_samples_split=2)
self_regr =  my_regressor(
    loss="mse",
    learning_rate=0.1,
    n_estimators=100,
    max_depth=3,
    min_samples_split=2)

In [3]:
%%time
sklearn_regr.fit(X_train, y_train)
sklearn_pred = sklearn_regr.predict(X_test)

CPU times: user 1.36 s, sys: 8.47 ms, total: 1.37 s
Wall time: 1.37 s

In [4]:
%%time 
self_regr.fit(X_train, y_train)
self_pred = self_regr.predict(X_test)

/opt/conda/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/conda/lib/python3.8/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

CPU times: user 6min 4s, sys: 449 ms, total: 6min 4s
Wall time: 6min 5s

In [5]:
print('Sklearn regressor MSE:', mean_squared_error(y_test, sklearn_pred, squared=True))
print('My regressor MSE: ', mean_squared_error(y_test, self_pred, squared=True))

Sklearn regressor MSE: 6.815331232536756
My regressor MSE:  6.687882667665732

#### Despite the fact, Gradient Boosting Regressor from the DS tool works much more faster, accuracy of my implementation is a little bit better